workflows:
  alpha_ios:
    name: AlphaWord iOS
    environment:
      xcode: latest
    scripts:
      - name: Show repo tree
        script: |
          set -euxo pipefail
          pwd
          ls -la
          echo "Swift files:"
          find . -maxdepth 3 -type f -name "*.swift" -print | sort || true
          echo "project.yml:"
          sed -n '1,160p' project.yml || true

      - name: Install XcodeGen & generate project
        script: |
          set -euxo pipefail
          brew install xcodegen || true
          xcodegen generate
          echo "--- xcodebuild -list ---"
          xcodebuild -list -project AlphaWord.xcodeproj

      - name: Compile for Simulator
        script: |
          set -euxo pipefail
          xcodebuild \
            -project AlphaWord.xcodeproj \
            -scheme "${SCHEME:-AlphaWord}" \
            -configuration Debug \
            -destination 'platform=iOS Simulator,OS=latest,name=iPhone 14' \
            PRODUCT_BUNDLE_IDENTIFIER="${BUNDLE_ID:-com.abdulla.alphaword.dev}" \
            build

      - name: Archive (with auto-provisioning)
        script: |
          set -euxo pipefail
          xcodebuild \
            -project AlphaWord.xcodeproj \
            -scheme "${SCHEME:-AlphaWord}" \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath $CM_BUILD_DIR/AlphaWord.xcarchive \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM="${DEVELOPMENT_TEAM_ID:-9M8ARAXQRV}" \
            PRODUCT_BUNDLE_IDENTIFIER="${BUNDLE_ID:-com.abdulla.alphaword.dev}" \
            CODE_SIGN_STYLE=Automatic \
            SDKROOT=iphoneos \
            archive

      - name: Export IPA
        script: |
          set -euxo pipefail
          cat > $CM_BUILD_DIR/exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0"><dict>
            <key>method</key><string>development</string>
            <key>signingStyle</key><string>automatic</string>
            <key>stripSwiftSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict></plist>
          EOF
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/AlphaWord.xcarchive \
            -exportOptionsPlist $CM_BUILD_DIR/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/export \
            -allowProvisioningUpdates
    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
