workflows:
  alpha_ios:
    name: AlphaWord iOS (deterministic)
    environment:
      xcode: latest
    scripts:
      - name: Show repo tree
        script: |
          set -euxo pipefail
          pwd
          ls -la

      - name: Create minimal app files (always)
        script: |
          set -euxo pipefail
          rm -rf App
          mkdir -p App

          cat > App/AlphaWordApp.swift <<'SWIFTA'
          import SwiftUI
          @main
          struct AlphaWordApp: App {
              var body: some Scene { WindowGroup { MainMenuView() } }
          }
          SWIFTA

          cat > App/MainMenuView.swift <<'SWIFTB'
          import SwiftUI
          struct MainMenuView: View {
              var body: some View {
                  VStack(spacing: 16) {
                      Text("AlphaWord").font(.system(size: 42, weight: .heavy, design: .rounded))
                      Text("Hello from Codemagic build").foregroundStyle(.secondary)
                  }.padding()
              }
          }
          SWIFTB

          cat > project.yml <<'YMLSPEC'
          name: AlphaWord
          options:
            developmentLanguage: en
          targets:
            AlphaWord:
              type: application
              platform: iOS
              deploymentTarget: "15.0"
              sources:
                - path: App
              info:
                properties:
                  CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
                  CFBundleName: AlphaWord
                  CFBundleShortVersionString: "1.0"
                  CFBundleVersion: "1"
                  UILaunchScreen: {}
              settings:
                base:
                  PRODUCT_BUNDLE_IDENTIFIER: $(BUNDLE_ID)
                  DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM_ID)
                  CODE_SIGN_STYLE: Automatic
                  SWIFT_VERSION: 5.0
                  IPHONEOS_DEPLOYMENT_TARGET: 15.0
          schemes:
            AlphaWord:
              build:
                targets:
                  AlphaWord: all
              run:
                config: Release
          YMLSPEC

          echo "Created files:"
          ls -la App
          echo "project.yml preview:"
          sed -n '1,200p' project.yml

      - name: Install XcodeGen & generate project
        script: |
          set -euxo pipefail
          brew install xcodegen || true
          xcodegen generate
          echo "--- xcodebuild -list ---"
          xcodebuild -list -project AlphaWord.xcodeproj

      - name: Compile for Simulator (sanity)
        script: |
          set -euxo pipefail
          xcodebuild \
            -project AlphaWord.xcodeproj \
            -scheme "${SCHEME:-AlphaWord}" \
            -configuration Debug \
            -destination 'platform=iOS Simulator,OS=latest,name=iPhone 14' \
            PRODUCT_BUNDLE_IDENTIFIER="${BUNDLE_ID:-com.abdulla.alphaword.dev}" \
            build

      - name: Archive (with auto-provisioning)
        script: |
          set -euxo pipefail
          xcodebuild \
            -project AlphaWord.xcodeproj \
            -scheme "${SCHEME:-AlphaWord}" \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath $CM_BUILD_DIR/AlphaWord.xcarchive \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM="${DEVELOPMENT_TEAM_ID:-9M8ARAXQRV}" \
            PRODUCT_BUNDLE_IDENTIFIER="${BUNDLE_ID:-com.abdulla.alphaword.dev}" \
            CODE_SIGN_STYLE=Automatic \
            SDKROOT=iphoneos \
            archive

      - name: Export IPA
        script: |
          set -euxo pipefail
          cat > $CM_BUILD_DIR/exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0"><dict>
            <key>method</key><string>development</string>
            <key>signingStyle</key><string>automatic</string>
            <key>stripSwiftSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict></plist>
          EOF
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/AlphaWord.xcarchive \
            -exportOptionsPlist $CM_BUILD_DIR/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/export \
            -allowProvisioningUpdates

    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
