workflows:
  alpha_ios:
    name: AlphaWord iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.abdulla.alphaword
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - ~/.cocoapods
    scripts:
      - name: Set up keychain to be used for code signing
        script: |
          keychain initialize
          
      - name: Install XcodeGen
        script: |
          brew install xcodegen
          
      - name: Generate Xcode project
        script: |
          xcodegen generate
          
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
          
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "AlphaWord.xcworkspace" \
            --scheme "AlphaWord" \
            --config "Release"
            
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - user@example.com
