workflows:
  alpha_ios_test:
    name: AlphaWord iOS Test Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      xcode: latest
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen
          
      - name: Generate Xcode project
        script: |
          xcodegen generate
          
      - name: Build for iOS Simulator
        script: |
          xcodebuild -project AlphaWord.xcodeproj \
            -scheme AlphaWord \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            clean build \
            CODE_SIGNING_ALLOWED=NO
            
    artifacts:
      - /tmp/xcodebuild_logs/*.log
