workflows:
  alpha_ios:
    name: AlphaWord iOS
    environment:
      xcode: latest
    scripts:
      - name: Diagnostics & install XcodeGen
        script: |
          set -euxo pipefail
          brew install xcodegen || true
          echo "Root:"
          pwd; ls -la
      - name: Generate Xcode project & list schemes
        script: |
          set -euxo pipefail
          xcodegen generate
          echo "Project files:"; ls -la
          xcodebuild -list -project AlphaWord.xcodeproj
      - name: Compile for Simulator (catch code errors fast)
        script: |
          set -euxo pipefail
          xcodebuild \
            -project AlphaWord.xcodeproj \
            -scheme "AlphaWord" \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            build
      - name: Archive (with auto-provisioning)
        script: |
          set -euxo pipefail
          xcodebuild \
            -project AlphaWord.xcodeproj \
            -scheme "AlphaWord" \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath $CM_BUILD_DIR/AlphaWord.xcarchive \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM="${DEVELOPMENT_TEAM_ID}" \
            PRODUCT_BUNDLE_IDENTIFIER="${BUNDLE_ID}" \
            CODE_SIGN_STYLE=Automatic \
            SDKROOT=iphoneos \
            archive
      - name: Export IPA
        script: |
          set -euxo pipefail
          cat > $CM_BUILD_DIR/exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0"><dict>
            <key>method</key><string>development</string>
            <key>signingStyle</key><string>automatic</string>
            <key>stripSwiftSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict></plist>
          EOF
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/AlphaWord.xcarchive \
            -exportOptionsPlist $CM_BUILD_DIR/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/export \
            -allowProvisioningUpdates
    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
