workflows:
  alpha_ios:
    name: AlphaWord iOS
    environment:
      xcode: latest
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen
      - name: Generate Xcode project
        script: |
          xcodegen generate
      - name: Archive
        script: |
          xcodebuild -scheme "AlphaWord" -configuration Release -destination 'generic/platform=iOS' -archivePath $CM_BUILD_DIR/AlphaWord.xcarchive archive
      - name: Export IPA
        script: |
          cat > $CM_BUILD_DIR/exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0"><dict>
            <key>method</key><string>development</string>
            <key>signingStyle</key><string>automatic</string>
            <key>stripSwiftSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict></plist>
          EOF
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/AlphaWord.xcarchive -exportOptionsPlist $CM_BUILD_DIR/exportOptions.plist -exportPath $CM_BUILD_DIR/export
    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
