name: AlphaWord
options:
  minimumXcodeGenVersion: 2.37.0
  createIntermediateGroups: true
targets:
  AlphaWord:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: App
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.abdulla.AlphaWord
      PRODUCT_NAME: AlphaWord
      INFOPLIST_FILE: App/Info.plist
      SWIFT_VERSION: 5.0
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      testTargets: []
packages: {}