name: AlphaWord
options:
  developmentLanguage: en
targets:
  AlphaWord:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: .
        excludes:
          - project.yml
          - codemagic.yaml
    info:
      path: Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(BUNDLE_ID)
        DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM_ID)
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: 5.0
        IPHONEOS_DEPLOYMENT_TARGET: 15.0
schemes:
  AlphaWord:
    build:
      targets:
        AlphaWord: all
    run:
      config: Release
