name: AlphaWord
options:
  bundleIdPrefix: com.abdulla
  developmentLanguage: en
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4

targets:
  AlphaWord:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: .
        excludes:
          - project.yml
          - codemagic.yaml
          - Info.plist
          - README.md
          - "*.md"
          - .git
          - .gitignore
          - build
        includes:
          - "*.swift"
    info:
      path: Info.plist
      properties:
        CFBundleName: AlphaWord
        CFBundleDisplayName: AlphaWord
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        LSRequiresIPhoneOS: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIRequiredDeviceCapabilities:
          - armv7
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.abdulla.alphaword
        SWIFT_VERSION: 5.0
        IPHONEOS_DEPLOYMENT_TARGET: 15.0
        TARGETED_DEVICE_FAMILY: 1,2
        SUPPORTS_MACCATALYST: false
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
        CODE_SIGN_IDENTITY: "Apple Development"
        PROVISIONING_PROFILE_SPECIFIER: ""
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          GCC_OPTIMIZATION_LEVEL: "0"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          GCC_OPTIMIZATION_LEVEL: "s"
    capabilities:
      - name: GameCenter
        enabled: true

schemes:
  AlphaWord:
    build:
      targets:
        AlphaWord: all
    run:
      config: Debug
      commandLineArguments:
        "": true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
